---
title: "R Notebook"
output: html_notebook
---


```{r, libraries}
library(tidyverse)
library(rstan)
library(loo)
rstan_options(auto_write = T)
options(mc.cores = parallel::detectCores())
source('../../2018-09 Apixiban Bayesian Models/stan_utilities.R')

```




```{r, need_this}
df = read_csv('Data/apixiban_regression_data.csv')

pk_curve = function(t,V,k_a,k){
  return( (2.5 / V) * (k_a / (k_a - k)) * ( exp(- k * t) - exp(-k_a * t) ))
}
pk_curve = Vectorize(pk_curve)
```
```{r,non_heriarchical_no_regression}
#--- non-herarchical regression ---
file.name = "Model Data/model_data_no_h_no_reg.R"
input_data <- read_rdump(file.name)

#Fit the model
fit = stan('Models/no_heirarchy_no_reg_model.stan',
           data = input_data)
params = rstan::extract(fit)
log_lik_1 <- extract_log_lik(fit, merge_chains = FALSE)
r_eff <- relative_eff(exp(log_lik_1)) 

check_all_diagnostics(fit)
loo_1 <- loo(log_lik_1, r_eff = r_eff, cores = 2)
plot(loo_1)




times = df$Time  
C = params$C_pred[,1:8] %>% apply(., 2, mean)
C_lims = params$C_ppc[,1:8] %>% apply(., 2, function(x) quantile(x, c(0.25, 0.975))) %>% t()

dfit = data_frame(C = C, C_l = C_lims[,1], C_u = C_lims[,2], t = unique(times) )

df %>% 
  ggplot(aes(Time, Concentration_scaled))+
  geom_line(aes(group = Subject), alpha = 0.5)+
  geom_smooth()+
  geom_line(data= dfit, aes(t,y = C), color = 'red')+
  geom_ribbon(data= dfit, aes(t, y = C,ymin = C_l, ymax = C_u), fill = 'red', alpha = 0.25)+
  theme(aspect.ratio = 1/1.61)


#TODO
#Write completely heirarhcical model.
```

```{r, heirarchical_no_regression}



file.name = "Model Data/model_data_heirarhcical_no_regression.R"

input_data <- read_rdump(file.name)

stan('Models/herarchical_no_regression.rds', data = input_data)

```

