---
title: "R Notebook"
output: pdf_document
---

```{r}
library(mgcv)
library(tidyverse)
library(rstan)
options(mc.cores = parallel::detectCores())


apixaban.data = read_csv('Data/ApixibanExperimentData.csv') %>% filter(Time>0)

```

```{r}
num.patients = length(unique(apixaban.data$Subject))
C_hat = apixaban.data$Concentration
measured_t = apixaban.data$Time
times = sort(unique(measured_t))

D = 2.5
t0 = 0
C0 = array(c(0), dim = 1)
N_t = length(measured_t)
N_tt = length(times)
ix = rep(seq_along(times),num.patients)
stan_rdump(c("t0", "C0", "D", "times", "N_t", "C_hat", 'N_tt', 'ix'), file="Data/one_comp_lin_elim_abs.data.R")
input_data <- read_rdump("Data/one_comp_lin_elim_abs.data.R")

```



```{r}
fit = rstan::stan(file = 'Models/model_1.stan',data = input_data, chains = 4)
```



```{r}
plot(fit, show_density = T)
```


```{r}
params = rstan::extract(fit)
```


```{r}

model.params = params[c('V','k','k_a','sigma')] %>% 
               as.data.frame()

colnames(model.params) = c('V','k','k[a]','sigma')

model.params %>% 
  gather(param,sample) %>% 
  ggplot(aes(sample))+
  geom_histogram(fill = 'gray', color = 'black')+
  facet_wrap(~param, nrow = 2, scale = 'free', labeller = label_parsed)



```


```{r}
model.preds = data_frame(Time = times,
                         Concentration = apply(params$C,2,median),
                         cred_int_l = apply(params$C,2, function(x) quantile(x,probs = c(0.025))),
                         cred_int_u = apply(params$C,2, function(x) quantile(x,probs = c(0.975)))
)

model.preds %>% 
  ggplot(aes(x = Time, y = Concentration))+
  geom_point(data = apixaban.data, aes(Time, Concentration), alpha = 0.25)+
  geom_line(color = 'red')+
  geom_ribbon(aes(ymin = cred_int_l, ymax = cred_int_u),color = 'red', alpha = 0.25)+
  labs(title = 'Credible Interval')

```

```{r}


model.ppc = data_frame(Time = times,
                         Concentration = apply(params$C_ppc,2,median),
                         cred_int_l = apply(params$C_ppc,2, function(x) quantile(x,probs = c(0.025))),
                         cred_int_u = apply(params$C_ppc,2, function(x) quantile(x,probs = c(0.975)))
)

model.ppc %>% 
  ggplot(aes(x = Time, y = Concentration))+
  geom_line(color = 'red')+
  geom_ribbon(aes(ymin = cred_int_l, ymax = cred_int_u),color = 'red', alpha = 0.25)+
  geom_point(data = apixaban.data, aes(Time, Concentration), alpha = 0.05)+
  labs(title = 'Posterior Predictive Check')

```

